name: Link Checker

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "**/*.html"
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.html"
  schedule:
    - cron: "0 18 * * *"          # 03:00 JST daily
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --timeout 20 --max-redirects 5 "**/*.md" "**/*.html"
          output: lychee/out.md
          fail: false                               # keep the job running even if links fail

      - name: Create or update issue
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken links report
          content-filepath: lychee/out.md
          labels: broken-links, automated
